### ISSUE TITLE
How to make myself as the owner of the server have infinite chunks?

### ISSUE THREAD

**Issue by Kittycraft0** [WasabiThumb/xclaim#104]
I can't figure it out and I can't find a tutorial to do so, i'd like to be able to claim city roads and city river so nobody else accidentally claims them and builds there. I tried messing around with luckperms but then my server started crashing whenever i claimed more than my previous max and then used the barrier block to leave the UI. I then unclaimed a thing and then tried to reclaim it but then it now said i was at my max even with less claims, as i had gotten rid of the sample-1 and sample-2 and changed the default to 4 chunks. Maybe i was set back to default even though i made a new owner group in the config.yml file.

I guess i'm doing a 1.21 purpur server and the support says 1.20 so maybe i can't be exactly talking here.

Here is my current config.yml file:
language: en-US # must match a language from lang/*.json
veteran-time: 300 # measured in seconds
stop-editing-on-shutdown: false
stop-editing-on-leave: true
auto-save:
  enabled: true
  interval: 300 # measured in seconds
exempt-claim-owner-from-permission-rules: true
enforce-adjacent-claim-chunks: true
allow-diagonal-claim-chunks: false
enter-chunk-editor-on-create: true
use-economy: false
limits:
  default:
     max-chunks: 4
     max-claims: 2
     max-claims-in-world: -1
  #    claim-price: 20
  #    unclaim-reward: 20
     free-chunks: 4
  # infiniteclaims:
  #   max-chunks: 500000
  #   max-claims: 100000
  owner:
     max-claims-in-world: -1
    max-chunks: 10000
    max-claims: 10000
  #sample-2:
  #  max-chunks: 25
  #  max-claims: 8
  #  give-after: 604800 # measured in seconds
dynmap-integration:
  enabled: true
  use-old-outline-style: false
  debug: false
worldguard-integration:
  enabled: true
  debug: false
disable-paper-warning: false
worlds:
  grace-time: 604800 # if a claim exists in a blacklisted world, the owner has this much time before it is removed (seconds)
  use-whitelist: false
  use-blacklist: false
  case-sensitive: true
  whitelist:
    - world
    - world_nether
    - world_the_end
  blacklist:
    - minigames
    - pvp
    - etc

**Comment by WasabiThumb** [comment]
Please use
```yaml
# code blocks
```
when pasting YAML. GitHub sees the # comments as MarkDown and converts it into headings, and also removes leading whitespace. This makes it essentially impossible for me to verify that your config is even valid YAML.

Anyways, what you want to do is to give yourself (or the Admin group) the permission ``xclaim.group.infiniteclaims``.
In general, when we have ``xclaim.group.X``, we inherit optimal values from ``xclaim.limits.X`` in the config.

Example (with user): ``/lp user @s permission set xclaim.group.infiniteclaims true``
Example (with group):
```
/lp group admins permission set xclaim.group.infiniteclaims true
/lp user @s group add admins
```

**Comment by WasabiThumb** [comment]
Does this answer your question? :)

**Comment by Kittycraft0** [comment]
yes, thanks!
