### ISSUE TITLE
Claim Mode players receive unmodified damage

### ISSUE THREAD

**Issue by ruk13xa** [WasabiThumb/xclaim#107]
If you get attacked in claim mode you get full damage(not wearing armor)

**Comment by WasabiThumb** [comment]
Please clarify:
1. Claim Mode players should be invulnerable
2. Claim Mode players should maintain the same damage modifications they had when they were not in Claim Mode; damage will be dealt as if they were wearing their retained armor
3. Claim Mode players should receive a certain percentage of the normal damage
4. Something else entirely

Whatever option you mean, this is definitely worth thinking about! Thanks for your feedback

**Comment by ruk13xa** [comment]
I think 2 is the best

**Comment by WasabiThumb** [comment]
Made [a commit](https://github.com/WasabiThumb/xclaim/commit/d29d96434b7b32f698f8cd5f294e2fa1d9166d4e) but needs to be tested

**Comment by WasabiThumb** [comment]
Staged for [1.14](https://github.com/WasabiThumb/xclaim/pull/121)
