### ISSUE TITLE
[Language Support] Turkish Language

### ISSUE THREAD

**Issue by Krayir5** [WasabiThumb/xclaim#123]
You helped me and i want to help you by adding turkish to the plugins language. If you want it too i'm gladly ready to add turkish to the plugin 🙂. I know that it's not that much a big deal but i just wanted to help

**Comment by WasabiThumb** [comment]
> You helped me and i want to help you by adding turkish to the plugins language. If you want it too i'm gladly ready to add turkish to the plugin 🙂. I know that it's not that much a big deal but i just wanted to help

Sure thing! Just make sure that the [MiniMessage tags](https://docs.advntr.dev/minimessage/format.html) stay intact and that the resulting file is [valid JSON](https://jsonchecker.com/). :)

**Comment by WasabiThumb** [comment]
Release 1.14 is otherwise ready, if you're fast I can sneak the translation in :)

**Comment by Krayir5** [comment]
> Release 1.14 is otherwise ready, if you're fast I can sneak the translation in :) Also let me know how I should credit you in the release notes.

You could do anyway you like, the translation will be ready in the next couple hours if you could wait a little bit

**Comment by Krayir5** [comment]
> Release 1.14 is otherwise ready, if you're fast I can sneak the translation in :) Also let me know how I should credit you in the release notes.

#126 It's done

**Comment by WasabiThumb** [comment]
Awesome! Thanks
