### ISSUE TITLE
[bug] trusted players page can completely crash the server

### ISSUE THREAD

**Issue by gocciolafr** [WasabiThumb/xclaim#135]
how to reproduce:

1. go to the trusted players page
2. press add player
3. type random name, for example "hello" (this is the one that made the server crash)
4. when the player is added simply click on the player head
5. after this the server crashes.

**Comment by gocciolafr** [comment]
i just noticed that almost everything you can type to the name, even if it is a real player it crashes the server. can you please push an update that temporarily removes this feature until fixed?

**Comment by WasabiThumb** [comment]
> how to reproduce:
> 
> 1. go to the trusted players page
> 2. press add player
> 3. type random name, for example "hello" (this is the one that made the server crash)
> 4. when the player is added simply click on the player head
> 5. after this the server crashes.

What is the stack trace/thread dump produced?

**Comment by RHX0R3** [comment]
Stumbled upon the same error. Thats quite fatal :(.

**[HERE](https://pastebin.com/U9GPrd4t)** is my stacktrace when it's crashed.

**Comment by Krayir5** [comment]
yeah it got fixed in the codes but i guess he didn't build it publicly, you can build the plugin yourself by just downloading and using maven it'll be fixed

**Comment by WasabiThumb** [comment]
lgtm, should be fixed in [1.14.1](https://github.com/WasabiThumb/xclaim/releases/tag/1.14.1)
