### ISSUE TITLE
Hoglin mssing in EntityGroup.isHostile

### ISSUE THREAD

**Issue by TheosRee** [WasabiThumb/xclaim#138]
Looking at your code and reading [EntityGroup#isMonster](https://github.com/WasabiThumb/xclaim/blob/master/src/main/java/codes/wasabi/xclaim/api/enums/EntityGroup.java#L46) I noticed that the missing Entities are "just" the few [Enemies](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Enemy.html) which does not implement Monster.
Looking at that I saw that you miss the Hoglin in your list.
I don't know if you want to modify the method to use the `Enemy` interface instead the `Monster` or just add the Hoglin to the list.

**Comment by WasabiThumb** [comment]
IIRC ``Enemy`` didn't exist when I wrote that code. I could go either way on this, but I'll definitely fix ^_^

**Comment by WasabiThumb** [comment]
Made a commit ([394e7ca](https://github.com/WasabiThumb/xclaim/commit/394e7ca77997bd2cce1371a1e3627c600b51a235)) but might be a while until I can test

**Comment by WasabiThumb** [comment]
See [1.14.2](https://github.com/WasabiThumb/xclaim/releases/tag/1.14.2)
