### ISSUE TITLE
Enhancement: claims per world

### ISSUE THREAD

**Issue by H7KZ** [WasabiThumb/xclaim#14]
Right now you can claim lets say 3 claims in world on 3 different places... so I don't want that. I want to only claim 1 claim per world. Or 2 claims per world - depended on config

**Comment by WasabiThumb** [comment]
Interesting idea, will probably be included in the next update.

**Comment by WasabiThumb** [comment]
This has been added and will be included in the next update. See the config section for info on how to manage. For example if you wanted everybody to only be able to make one claim in each world, you would set ``limits.default.max-claims-in-world`` to ``1``.

**Comment by H7KZ** [comment]
oh you are a fast programmer... :D I was just finishing my own version of the per world claims :( no PR for me ig

**Comment by WasabiThumb** [comment]
Appreciate it :D
