### ISSUE TITLE
TnT machine explode the land?

### ISSUE THREAD

**Issue by Jamelos** [WasabiThumb/xclaim#152]
Hey. I am sorry that I'm posting this here, but I am extremely worried that some friends will create a slime-powered flying blaster and break my base... does that work? Or will the TnT act like it was lit by them? Thank you!

**Comment by WasabiThumb** [comment]
> Hey. I am sorry that I'm posting this here, but I am extremely worried that some friends will create a slime-powered flying blaster and break my base... does that work? Or will the TnT act like it was lit by them? Thank you!

IIRC the only way to prevent this is to set the permission to NONE. There will always be a system complicated enough to make the server lose track of the TNT source, or hang the server trying. Consider the extent to which Vanilla redstone can be abused to cause lag; now consider propagating cause data, and clearing it such that 2 people can click the same button and have the result obey different permissions.

If the permission is set to VETERAN or TRUSTED, XClaim will _try_ to identify the source- see [here](https://github.com/WasabiThumb/xclaim/blob/e65b09316cfeb8029323ed69e1de62824535d4e1/src/main/java/codes/wasabi/xclaim/api/enums/permission/handler/ExplosionHandler.java#L56). This uses data that can be accessed readily, so it's easily fooled.

Let me know if this answers your question. :)

**Comment by Jamelos** [comment]
So, if the source is unknown, will it explode or not?

**Comment by WasabiThumb** [comment]
If the source is unknown, it will be blocked only if the explosion permission is set to NONE.

**Comment by Jamelos** [comment]
Thank you so much for answering.As for the second question, if they explode a TnT just outside of the border, will the claim blocks inside the border be affected? Because liquids like lava can pass through and create a wall of ugly cobblestone... Will the same happen with TnT?

**Comment by WasabiThumb** [comment]
> Thank you so much for answering.As for the second question, if they explode a TnT just outside of the border, will the claim blocks inside the border be affected? Because liquids like lava can pass through and create a wall of ugly cobblestone... Will the same happen with TnT?

The check uses the "location" of the TNT, which the game considers to be the bottom center. So if the "location" falls within a chunk where it would be denied, the explosion is completely blocked. This includes blocks that would technically fall outside of the claim.

**Comment by RHX0R3** [comment]
> > Thank you so much for answering.As for the second question, if they explode a TnT just outside of the border, will the claim blocks inside the border be affected? Because liquids like lava can pass through and create a wall of ugly cobblestone... Will the same happen with TnT?
> 
> The check uses the "location" of the TNT, which the game considers to be the bottom center. So if the "location" falls within a chunk where it would be denied, the explosion is completely blocked. This includes blocks that would technically fall outside of the claim.

Just read through this issue.

For the location: Could that be hooked in and modified, before it is checked and (possibly) blocked?
Something like: `e.getLocation().add(0.5, 0, 0.5)`;

I have a quite limited knowledge on API usage, or how to properly use the EventHandler.
But in theory it _could_ point to a solution, no?

Best regards,
X0R3

**Comment by RHX0R3** [comment]
The issue kind of reminds me of #158.

**Comment by WasabiThumb** [comment]
As mentioned, the actual problem with attempting to fix this in the current system is that every single affected block needs to be checked, including for massive non-Vanilla explosions that may have a multi-chunk radius. In this case, the number of queries grows in some proportion to ``n^2``, which will undoubtedly destroy the server. No Vanilla explosion has a 2+ chunk radius, so if regular TNT is your only concern, claiming 1 extra chunk on edges completely fixes the problem. Should be entirely addressed in v2.

**Comment by WasabiThumb** [comment]
First "working" build of v2 is here

https://github.com/user-attachments/assets/cafcefe8-f22b-4629-bf6e-61f4eb4e83fa
