### ISSUE TITLE
Players can obtain barrier blocks through the claiming interface

### ISSUE THREAD

**Issue by tt-thoma** [WasabiThumb/xclaim#154]
## This issue had already been addressed in #59 but it seems that it isn't patched, at least not in the latest versions:

> Paper 1.21.3 - build 36
> XClaim 1.15.1 ([SpigotMC website](https://www.spigotmc.org/resources/1-8-1-21-xclaim-better-chunk-claiming-for-smps.102843/))

**The glitch hasn't changed:**
1. Place an item frame
2. Create a new claim
3. In the claim menu, you have a barrier block - click on the item frame with it
4. Quit the server
5. Rejoin and take the barrier block from the frame

https://github.com/user-attachments/assets/6afb43c9-27d1-4cf4-a9f6-67c442c98bcc

**As a temporary fix, you can put this command in repeating command blocks (tested on 1.21.3):**
> `/kill @e[type=minecraft:item_frame, nbt={Item: {id:"minecraft:barrier"}}]`
> `/kill @e[type=minecraft:glow_item_frame, nbt={Item: {id:"minecraft:barrier"}}]`

https://github.com/user-attachments/assets/6803bc1b-9fae-4f72-beea-51d4b52a4b1d

**Comment by WasabiThumb** [comment]
This is fixed in the imminent v2 release but seeing as this is a critical issue I don't mind patching it quickly

**Comment by tt-thoma** [comment]
Do note that disabling automatic closing of the claim menu when leaving does not fix it/make people attempting the glitch stuck because you can still exit by clicking an empty hotbar slot

**Comment by WasabiThumb** [comment]
Also seems Paper-specific as Spigot does not physically have ``PlayerItemFrameChangeEvent``, and its inclusion likely diverts the code path away from ``PlayerInteractEvent`` which is already caught & neutralized

**Comment by WasabiThumb** [comment]
Here's the dev build (from [this branch](https://github.com/WasabiThumb/xclaim/tree/bug/item-frame-smuggling)), won't be able to test myself for at least a few hours.
[xclaim-1.15.1.jar](https://file.io/xobMhxpWOHJ8)

**Comment by RHX0R3** [comment]
Works! Can't interact with an item frame anymore, when in editing mode - nice!
Thank you for the fast fix.

**Comment by RHX0R3** [comment]
Will 1.21.4 also work? Can't upgrade yet, since Paper is currently not _fully_ released for 1.21.4.

**Comment by WasabiThumb** [comment]
> Will 1.21.4 also work? Can't upgrade yet, since Paper is currently not _fully_ released for 1.21.4.

I don't see why not, since XClaim doesn't use any bleeding API or server internals. It broke for ~1.20 due to using server internals via ParticleLib, but ParticleLib is now completely removed from the plugin. It's fetched automatically for older servers. That being said, you never really know until you try.

**Comment by RHX0R3** [comment]
![grafik](https://github.com/user-attachments/assets/a6ed2b23-1c26-4f1a-9fe6-18538a3ee103)

Still works with Allays! :o

**Comment by RHX0R3** [comment]
![grafik](https://github.com/user-attachments/assets/fc96e388-8fbf-419b-8391-173b2c6754f6)

Also with Armor Stands :/

**Comment by WasabiThumb** [comment]
😐 The scope of exceptions to the interaction system never ceases to amaze me. Feel free to create another issue.
