### ISSUE TITLE
Can you change the default permissions when claiming a new chunk?

### ISSUE THREAD

**Issue by Tr3x30** [WasabiThumb/xclaim#155]
As a server administrator, I would like to disable the ability to toggle some of the options, however I also want to make it so that those actions are available for everyone by default.

E.g. Disabling the ability to toggle use flammables for claim owners; but having it on by default for everyone.

Does this happen automatically when disabling the toggle or is there a different way to accomplish that?

**Comment by Paperboypaddy** [comment]
I also want this feature. As a claim plugin id expect to set "Default" permissions for claims and or locking people out of editing said permissions on my server. I'm using this plugin on a smp of friends that still need to build on other players land without the hassle of allowing per player. I'm using this more just to mark territory and display it on BlueMap.

**Comment by WasabiThumb** [comment]
Added by #160, will be included in next release
