### ISSUE TITLE
Update German translation

### ISSUE THREAD

**Issue by eingruenesbeb** [WasabiThumb/xclaim#25]
Hey, I've noticed some changes to the language files and the translation was a bit off... Well I guess it was Google Translate. (You could just paste in the English translations into the files and message me at via e-mail: agreenbeb@gmail.com, whenever I should update something) I've also restored parity between the English and German README. 
I've already made the pull requests, so you can just merge them.

**Comment by WasabiThumb** [comment]
Thank you so much! Yes I just used google translate as a temporary solution lol. I didn't want to just assign you to an issue or something because its rather presumptuous but I'll definitely remember that for the future. Will merge and many thanks

**Comment by WasabiThumb** [comment]
I should add that the chinese translation got the same treatment, and I am even MORE clueless about how chinese works than german if you could believe it. But I don't think that Snow is likely interested in maintaining the translation

**Comment by eingruenesbeb** [comment]
You're welcome ;)
And with future additions to the language files, I'd suggest, what I wrote earlier, to just paste in the english version of the translation, as that way it keeps all it's original meaning (google translate might mangle that otherwise). You could also add a note (either directly in the translation file in the values such as `(not translated) [...]` or as a warning on load, that translations might not be 100% complete).
Feel free to assign me to any issue regarding the german translation. As for other languages... hmm, you could add a little text to the spigot page stating, that anyone is welcome to submit translations.
