### ISSUE TITLE
Renaming claims

### ISSUE THREAD

**Issue by Manu-Devloo** [WasabiThumb/xclaim#30]
If I try to rename a claim, the text shows up to type the name, but if I type it, it just sends a message in chat.

**Comment by WasabiThumb** [comment]
Any errors in console?

**Comment by Manu-Devloo** [comment]
Now that I check, i get this error: Could not pass event AsyncPlayerChatEvent to XClaim v1.9.5

**Comment by WasabiThumb** [comment]
> Now that I check, i get this error: Could not pass event AsyncPlayerChatEvent to XClaim v1.9.5

Erm.. I figured, but stack traces usually contain more information than that. Are you having the same issue as [this guy](https://www.spigotmc.org/threads/1-8-1-19-xclaim-better-chunk-claiming-for-smps.561776/page-3#post-4486277)?

**Comment by WasabiThumb** [comment]
Could you tell me if this build fixes the issue?
https://wasabicodes.xyz/cdn/e35ca93e139d1fd4186a7cc1dbf26983/xclaim-1.9.6.jar

**Comment by Manu-Devloo** [comment]
i will try that build now bit i only get the error i send you multiple times nothing more
