### ISSUE TITLE
[Bug] Issue when using rockets for elytra in claimed chunks.

### ISSUE THREAD

**Issue by eingruenesbeb** [WasabiThumb/xclaim#31]
Hello,
A player has brought to my attention, that, whenever you use rockets for an elytra boost, the boost activates, but the rocket doesn't get consumed. This effectively "dupes" the item or rather makes it infinitely usable. It's not a huge deal, as rockets are quite cheap, but it's a dupe nonetheless.
Now I saw that first hand by spectating said player and could confirm the result on a test server, if the "Interact" permission is disabled for the player.
A possible fix would be greatly appreciated.
~ Beb

**Comment by WasabiThumb** [comment]
> Hello, A player has brought to my attention, that, whenever you use rockets for an elytra boost, the boost activates, but the rocket doesn't get consumed. This effectively "dupes" the item or rather makes it infinitely usable. It's not a huge deal, as rockets are quite cheap, but it's a dupe nonetheless. Now I saw that first hand by spectating said player and could confirm the result on a test server, if the "Interact" permission is disabled for the player. A possible fix would be greatly appreciated. ~ Beb

This seems like an oversight in Spigot or Paper, I will have to make a workaround

**Comment by eingruenesbeb** [comment]
Alright, hopefully nothing too complicated. Removing the 
item from the player manually should do the trick, I guess.

**Comment by WasabiThumb** [comment]
I did silently fix this at some point and forgot to update the issue, if you're still having issues feel free to reopen
