### ISSUE TITLE
where can i look for /particle

### ISSUE THREAD

**Issue by ProjectSurvivalNetwork** [WasabiThumb/xclaim#35]
i need /particle

**Comment by WasabiThumb** [comment]
Sorry I never responded to this, what's the problem?
/particle was added to the game in 1.8, so you should have the command. I imagine that what is happening is that some other plugin is shadowing the vanilla /particle command with it's own /particle command, which I am not doing. It's likely some other plugin that is causing this issue, or it could potentially be ParticleLib however I very much doubt it. In any case, you can access the original command by doing:

/minecraft:particle

This works for any vanilla command, e.g. /minecraft:give, /minecraft:tell, etc. Very useful for when plugins such as Essentials use generic names that shadow the vanilla ones.
