### ISSUE TITLE
Compatibility with Bluemap

### ISSUE THREAD

**Issue by matheeuslima** [WasabiThumb/xclaim#36]
add compatibility with Bluemap plugin

**Comment by WasabiThumb** [comment]
Will consider but may be a while

**Comment by WasabiThumb** [comment]
BlueMap integration is currently being tested. Stay tuned for the next update
![image](https://user-images.githubusercontent.com/29989488/219531144-9757cae7-9df7-4e3b-9dfe-5d13ace43910.png)

**Comment by WasabiThumb** [comment]
Basic support has been added to 1.10.0, tweaks coming soon
