### ISSUE TITLE
Permission's In Claims

### ISSUE THREAD

**Issue by BatManNinia** [WasabiThumb/xclaim#39]
I currently have EssentialsX, Essentials_WarpGUI, WorldGuard, ChunkLoader, LinkNSync, LuckPerms, PlaceholderAPI, SimpleWarp and XClaim on my 1.19 Java server, (gave you that list to see if maybe its one of those plugins causing the issue) and when players walk into a claimed chunk and don't have permission there, they literally can't do anything, they can't eat, hit hostile mobs or anything, I just want people to be able to eat and kill hostile mobs in a claimed chunk.

**Comment by WasabiThumb** [comment]
The claim has to be configured to allow interactions. The default permission level for interactions is VETERAN, so if players have been on the server for a while then they will be able to interact in chunks.
