### ISSUE TITLE
Claims are gone after Server restart

### ISSUE THREAD

**Issue by trueflare** [WasabiThumb/xclaim#41]
I have the problem that all claims are gone after a server restart as if they never existed! Could anyone help me there? I've tried a few things but nothing works!

**Comment by WasabiThumb** [comment]
Are you sure that the server is exiting normally? It needs to close without a SIGKILL or similar so that the claims config can be saved properly when closed. Though the plugin should maybe have an autosave interval.

**Comment by trueflare** [comment]
The server only restarts itself with an auto restart plugin.  The plugin has set fixed times, but I can also prefer a restart with a command.  The restart routine looks like this:
1. the plugin executes save-all
2. /restart

**Comment by WasabiThumb** [comment]
There are changes pending that may be able to resolve your issue, I'll keep you posted. As a temporary fix you could set up a repeating task to auto-save the claims.

**Comment by WasabiThumb** [comment]
See if the auto-save feature in 1.10.1 helps you with this problem
