### ISSUE TITLE
Do not allow claiming of chunks around a certain radius

### ISSUE THREAD

**Issue by ShadiestGoat** [WasabiThumb/xclaim#44]
Is there a way to not allow users to claim a certain radius? Or even better, to claim the radius under an 'admin' account that is not connected to any player?

**Comment by WasabiThumb** [comment]
You can use WorldGuard, I believe I made it so that you can't claim chunks that occlude a WorldGuard region unless you have admin override

**Comment by ShadiestGoat** [comment]
I don't think thats true, I was just testing with a player without admin perms and they managed to claim a world guarded region

**Comment by WasabiThumb** [comment]
> I don't think thats true, I was just testing with a player without admin perms and they managed to claim a world guarded region

Ensure that the integration is enabled in the config? Set ``worldguard-integration.enabled`` to true in the config, it seems to be ``false`` by default and indeed the PR is titled "experimental worldguard integration", I remember having to put down this project for a while so it may be half-baked and have good reasons to be off by default.

**Comment by WasabiThumb** [comment]
Assuming this has been solved
