### ISSUE TITLE
[folia][error]Scheduling chunk load off-main , claims.yml got wiped

### ISSUE THREAD

**Issue by hkkongou** [WasabiThumb/xclaim#47]
full error log:
https://paste.denizenscript.com/View/110952

![image](https://github.com/WasabiThumb/xclaim/assets/61608872/0149bc25-4b1e-45b3-985a-e36fc2cb5ebe)

steps:
1.start folia server
2.make 1 claim
3.restart server
4.plugin cannot be loaded , claims.yml becomes blank 
[5.] after claims.yml got reset, claims cannot be found again but server  can start

problem does not occur when there is no claim in the server and the server got restart, and seems like only occur when claim(s) is created

**Comment by WasabiThumb** [comment]
It's fixed, uploading now

**Comment by WasabiThumb** [comment]
Fixed in release [1.10.3](https://github.com/WasabiThumb/xclaim/releases/tag/1.10.3)
