### ISSUE TITLE
Not working on 1.20.1

### ISSUE THREAD

**Issue by oliver194** [WasabiThumb/xclaim#50]
The plugin does start after running the paper server, and it has some errors, https://pastebin.com/jkv52TUy

Server version: Paper 1.20.1 (git-Paper-37)

**Comment by WasabiThumb** [comment]
This is not the important part of the error, it's likely further up.

**Comment by UsrBinLuna** [comment]
tested and working on MC 1.20/.1 Paper with XClaim 1.10.1 (1.10.2+ not working), after taking a look at the codebase the error seems to be caused by Folia detection. Error on 1.10.2+: [pastebin](https://pastebin.com/YRa10KRQ)

**Comment by WasabiThumb** [comment]
It should be catching that so this is weird but I'll look when I get the chance

**Comment by WasabiThumb** [comment]
Please see if 1.10.5 fixes this problem:
https://github.com/WasabiThumb/xclaim/releases/tag/1.10.5

**Comment by PixelboysTM** [comment]
Using Paper-Mc Server version 1.19.4 and XClaim version 1.10.5 and also having the same issue with failing to detect folia, which causes the plugin to be disabled by Paper.

**Comment by WasabiThumb** [comment]
> Using Paper-Mc Server version 1.19.4 and XClaim version 1.10.5 and also having the same issue with failing to detect folia, which causes the plugin to be disabled by Paper.

Please include a stack trace, though if it failed to detect folia it would use the Paper platform and thus work perfectly fine on a paper server :)

**Comment by oliver194** [comment]
it works now thanks
