### ISSUE TITLE
[Feature Request] Claim Protections True/False Config or Permissions

### ISSUE THREAD

**Issue by RillSoji** [WasabiThumb/xclaim#56]
I run a lot of SMP servers and many of them like the claim protections offered but I have a few who are trying to keep the vanilla experience as much as possible while not driving their moderation teams crazy. I adore this plugin because of it's simplicity compared to the others and will be implementing it on more servers. I would be able to use it for the vanilla-leaning clients too if I had a config or permissions node that turned off the protections so it's basically just the ability to name and claim. Thank you!

**Comment by BaksteenTM** [comment]
So if i understand correctly basically the ability to enable or disable the following things in server config settings?
Like to have the abilitiy to turn off the possibility for players to control the setting.

permissions:
ENTITY_DAMAGE_FRIENDLY: TRUSTED
ITEM_DROP: TRUSTED
ENTITY_DAMAGE_MISC: TRUSTED
ENTITY_DAMAGE_HOSTILE: TRUSTED
VEHICLE_PLACE: TRUSTED
ENTITY_DAMAGE_VEHICLE: TRUSTED
ENT_PLACE: TRUSTED
ENTER: TRUSTED
ENTITY_DAMAGE_NL: TRUSTED
DELETE: TRUSTED
INTERACT: TRUSTED
MANAGE: TRUSTED

**Comment by RillSoji** [comment]
Been a hot minute but I believe that is correct. Being able to turn off the possibility for players to control any or all claim settings.

**Comment by WasabiThumb** [comment]
You will be be able to remove permissions from the GUI layout when #22 is resolved.

**Comment by WasabiThumb** [comment]
Possible in a round-about way in [1.15.0](https://github.com/WasabiThumb/xclaim/releases/tag/1.15.0) by editing the layout files (see example [here](https://github.com/WasabiThumb/xclaim?tab=readme-ov-file#config-gui-layouts)). Feel free to make a new issue if this system does not serve your purposes.
