### ISSUE TITLE
[Feature Request] Min Distance between claims

### ISSUE THREAD

**Issue by RillSoji** [WasabiThumb/xclaim#57]
I would love to have a config that lets you set a minimum chunk distance between claims with an error telling the player they are too close to another player's claim. Maybe have the default be 8 chunks which should be 2 chunks within the default simulation distance. Some of my larger SMP servers require a minimum distance between bases so you're not loading your neighbors entities and farms. This would help resolve a lot of their cooperation issues there. Thanks for considering!

**Comment by WasabiThumb** [comment]
Added as ``claim-min-distance`` in b4c59c5. This issue will automatically be closed when ``dev/1.13`` is merged into master (and plugin version ``1.13.0`` is released).
