### ISSUE TITLE
Error while building Xclaim: no access to java.lang.Record

### ISSUE THREAD

**Issue by derjungeinhd** [WasabiThumb/xclaim#82]
I wanted to update my repo and build my modified version of xclaim, but now not a single version, even unmodified, wants to compile. I always get an error in WorldGuardProtectionService.java:50 "connot access java.lang.Record". Online I only find references to a bug with Android SDK but that shouldn't apply to this plugin. Does anybody else have this issue?!?!

**Comment by derjungeinhd** [comment]
Updating Intellij and all plugins, Downgrading the worldguard dependency in pom.xml to 7.0.9-SNAPSHOT, syncing it with maven and then updating it again to 7.1.0-SNAPSHOT seems to fix the issue. No idea why tbh.

**Comment by derjungeinhd** [comment]
Updating Intellij and all plugins, Downgrading the worldguard dependency in pom.xml to 7.0.9-SNAPSHOT, syncing it with maven and then updating it again to 7.1.0-SNAPSHOT seems to fix the issue. No idea why tbh.

**Comment by WasabiThumb** [comment]
The latest WorldGuard API uses Records, which are a Java 14+ feature. XClaim is designed to be compatible for MC 1.8, so it uses Java 8 as it's language version, but it is still required to use a Java 14+ (ideally Java 17) JDK to build the project.
