### ISSUE TITLE
How to stop the spam in the logs?

### ISSUE THREAD

**Issue by CtrlAiDel** [WasabiThumb/xclaim#90]
Hi, Thank you for the great plugin.

I am looking how to stop this from spamming in the console:
Xc saving claim spam log

I've found those settings, but I don't want to change them really...

auto-save:
  enabled: true
  interval: 300 # measured in seconds

What would turning off saving will do? My claim wouldnt be saved ? I don't want.

Please help me turn of these logs, or maybe add an option if ever possible in an update pretty please!? Thanks  alot!

**Comment by WasabiThumb** [comment]
The auto-save feature is not _necessary_, it's a failsafe. When the plugin shuts down it also saves all claims. The auto-save interval means that even if the server has a fatal crash, skipping the plugin shutdown process, the claim data will still be relatively recent.

Adding a config option to make the auto-save task silent is a fine idea. I will add that when I get the chance (maybe tommorow; EST) :)

**Comment by CtrlAiDel** [comment]
No rush, I really appreciate the help, the plugin and the quick follow up ! 

Thank you

**Comment by WasabiThumb** [comment]
I made [a commit](https://github.com/WasabiThumb/xclaim/commit/bd8cba38c5064d502d97bf29ab9ad88015336acc) for this, but I won't be able to test it myself for a while. Here's a [courtesy build](https://file.io/4dr74oDGo83R) if you wanted to try it.

![XClaim_1_13_1_jar](https://github.com/user-attachments/assets/98fb4f5f-0665-4e78-b821-26c71820677d)

**Comment by CtrlAiDel** [comment]
Thank you ill test that tonight

**Comment by CtrlAiDel** [comment]
It is working flawlessly! Thank you sir!
