### ISSUE TITLE
Bluemap integration not working

### ISSUE THREAD

**Issue by Kan0Ka** [WasabiThumb/xclaim#98]
So my bluemap integration is not working, only 1 claim out of like 20 are showing

- Paper 1.20.4
- Newest Bluemap
- Newest XClaim

**Comment by Kan0Ka** [comment]
It seem to work now

**Comment by WasabiThumb** [comment]
Anything you might have done that fixed or caused the issue? 😅

**Comment by Kan0Ka** [comment]
Now i can only see 1-2 claims again...
Idk what i did
