### ISSUE TITLE
Player able to place water with water buckets?

### ISSUE THREAD

**Issue by Kan0Ka** [WasabiThumb/xclaim#99]
One of my players found that you can place water with water bucket when aren't looking directly at a block where the outline comes out.

- Paper 1.20.4
- Newest XClaim

**Comment by WasabiThumb** [comment]
Do you think you could get it on video? There's a lot of things that might cause this

**Comment by Kan0Ka** [comment]
Sure i can try to get a video of it when i get on later :)

**Comment by WasabiThumb** [comment]
Any update on this?

**Comment by WasabiThumb** [comment]
WIll reopen when able to reproduce
